version: '3'

services:
  nginx:
    image: nginx:1.13.8
    container_name: thesignal-realtalk
    volumes:
      - ./configs/${MODE}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${DATA_PATH}/logs/nginx/:/var/log/nginx/
    environment:
      - HOST_PATH=${HOST_PATH}
    ports:
      - "4100:80"
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ${DATA_PATH}/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  ghost:
    build: ./configs/${MODE}/ghost
    container_name: thesignal-realtalk-ghost
    volumes:
      - ${DATA_PATH}/content:/var/lib/ghost/content
      - ${DATA_PATH}/logs/ghost:/var/lib/ghost/content/logs
      - ./src:/var/lib/ghost/content/themes/thesignal-realtalk
      - ./static/semantic/dist:/var/lib/ghost/content/themes/thesignal-realtalk/assets/semantic/
      - ./static/jquery/dist:/var/lib/ghost/content/themes/thesignal-realtalk/assets/jquery/
      - ./static/sugar/dist:/var/lib/ghost/content/themes/thesignal-realtalk/assets/sugar/
      - ./static/fonts:/var/lib/ghost/content/themes/thesignal-realtalk/assets/fonts
    restart: always
    ports:
      - "4101:2368"
    depends_on:
      - mysql
    environment:
      NODE_ENV: ${MODE}
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}
      mail__transport: ${GHOST_mail__transport}
      mail__from: ${GHOST_mail__from}
      mail__options__service: ${GHOST_mail__options__service}
      mail__options__auth__user: ${GHOST_mail__options__auth__user}
      mail__options__auth__pass: ${GHOST_mail__options__auth__pass}
      url: ${WEB_PATH}
    entrypoint: ["wait.sh", "mysql", "--", "docker-entrypoint.sh"]
    command: ["node", "current/index.js"]
  node:
    image: "node:8"
    container_name: thesignal-realtalk-api
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - HOST_PATH=${HOST_PATH}
      - GHOST_KEY=${GHOST_KEY}
      - GHOST_API_PATH=${GHOST_API_PATH}
      - RECAPTCHA=${RECAPTCHA}
      - RECAPTCHA_KEY=${RECAPTCHA_KEY}
    volumes:
      - ./api/:/home/node/app
    ports:
      - "4102:3000"
    command: "npm start"
