version: '3'

services:
  nginx:
    image: nginx:1.13.8
    container_name: thesignal-realtalk
    volumes:
      - ./config-nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4100:80"
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: blog-user
      MYSQL_PASSWORD: supersecret
  ghost:
    build: ./config-ghost
    container_name: thesignal-realtalk-ghost
    volumes:
      - ./content:/var/lib/ghost/content
      - ./logs:/var/lib/ghost/content/logs
      - ./src:/var/lib/ghost/content/themes/thesignal-realtalk
      - ./static/semantic/dist:/var/lib/ghost/content/themes/thesignal-realtalk/assets/semantic/
      - ./static/jquery/dist:/var/lib/ghost/content/themes/thesignal-realtalk/assets/jquery/
      - ./static/sugar/dist:/var/lib/ghost/content/themes/thesignal-realtalk/assets/sugar/
      - ./static/fonts:/var/lib/ghost/content/themes/thesignal-realtalk/assets/fonts
    restart: always
    ports:
      - "4101:2368"
    depends_on:
      - mysql
    environment:
      NODE_ENV: development
#      database__client: sqlite3
#      database__connection__filename: "/var/lib/ghost/content/data/ghost.db"
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: blog-user
      database__connection__password: supersecret
      database__connection__database: db
      url: "http://local.realtalkpenn.com/"
    entrypoint: ["wait.sh", "mysql", "--", "docker-entrypoint.sh"]
    command: ["node", "current/index.js"]
  node:
    image: "node:8"
    container_name: thesignal-realtalk-api
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./api/:/home/node/app
    ports:
      - "4102:3000"
    command: "npm start"
